# Site settings
title: X Blog
SEOTitle: X师傅的博客 | X Blog
header-img: img/post-bg-hacker.jpg
email: xhuang_olala@163.com
description: "Hi, friend, 好久不见, 这里是Data Scientist -- 爱健身的X师傅小站"
keyword: "Mr.X, X's Blog, X师傅, 数据可视化, 数据科学, 深度学习, AI, 人工智能, python"
url: "http://pickpikyup.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/pickpikyup/pickpikyup.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "发量惊人的AI算法工程师"
sidebar-avatar: /img/mrx_head.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     pickpikyup
# zhihu_username:     pickpikyup
github_username:    pickpikyup
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   pickpikyup
linkedin_username: xuanqi-huang-599a62140



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: pickpikyup

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 81de3a932ac101e28903                            #生成的clientID
  clientSecret: 37644d311192093d77fc10edc4940671130299c1    #生成的clientSecret
  repo: pickpikyup.github.io    #仓库名称
  owner: pickpikyup    #github用户名
  admin: pickpikyup
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: edee28b37e71337176fe9ee8fa407ad9
             

# Google Analytics
ga_track_id: 'UA-169442149-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#         title: "WY",
#         href: "http://zhengwuyang.com"
#     },{
#         title: "简书·MrX",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
